### ISSUE TITLE
why the Cmd didn't execute?

### ISSUE THREAD

**Issue by Zhang-WJ** [Zaid-Ajaj/login-sample-initial#1]
| Login Started ->
        let nextState = { state with LoginAttempt = InProgress }
        let login = async {
            let! loginResult = Api.login state.Username state.Password
            return Login (Finished loginResult)
        }
        
        let nextCmd = Cmd.fromAsync login
        nextState, nextCmd

when I did follow your book, when finish the simple "login-sample-initial", when I enter the username and password, it stay in step 2 "InProgress", and don't continue execute the "

**Comment by Zaid-Ajaj** [comment]
Hi there, the code looks good and it should execute the command. My guess is that the message Login (Finished loginResult) is being intercepted in the parent component on a successful login attempt. Can you please whether that is the case?

**Comment by Zhang-WJ** [comment]
Thanks! I have found the error,
module Cmd =
    let fromAsync (operation: Async<'msg>) : Cmd<'msg> =
        let delayedCmd (dispatch: 'msg -> unit) : unit =
            let delayedDispatch = async {
                match! Async.Catch operation with
                | Choice1Of2 msg -> **dispatch** msg
                | Choice2Of2 error -> ignore()
            }

            Async.StartImmediate delayedDispatch

        Cmd.ofSub delayedCmd

I forget dispatch the msg.
thanks again!
